version: '2'

services:
    # =-=-=-=-= ANGULAR =-=-=-=-=
    angular:
      build:
        context: .
        dockerfile: Dockerfile.dev
      container_name: LWAngular2_dev
      ports:
        - "4200:4200"
      volumes:
        - .:/home/app/lovohhwebsite
        - /home/app/lovohhwebsite/node_modules
