version: '2'

services:
    # =-=-=-=-= Nginx =-=-=-=-=
    nginx:
      build:
        context: .
        dockerfile: Dockerfile.prod
      container_name: LWNginx
      ports:
        - "80:80"
        - "443:443"
      restart: always
