FROM nginx
LABEL maintainer = "Hector Lovo <lovohh@gmail.com>"

# Copies the "production" version of the app into /srv.
# NOTE: This assumes that the directory ./dist exists locally.
COPY ./dist/ /usr/share/nginx/html

RUN mkdir -p /etc/nginx/ssl/
