version: 2

# Settings common to each job.
anchor_1: &defaults
  working_directory: ~/lovohhwebsite
  docker:
    - image: circleci/node:8.9-stretch-browsers

# Restore cache based on package-lock.json checksum for branch.
anchor_2: &restore_cache_defaults
    keys:
      - lovohhwebsite-cache-{{ checksum "package-lock.json" }}
      # fallback to using the latest cache if no exact match is found
      - lovohhwebsite-cache-

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_defaults
      - run: node --version && npm --version
      - run: npm install --no-save
      - run: npm run build
      - save_cache:
          key: lovohhwebsite-cache-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_defaults
      - run: npm run test

  deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.11.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
      - run:
          name: Push to DockerHub
          command: |
            docker build -f ./Dockerfile.prod -t lovohh/lovohhwebsite:$CIRCLE_SHA1 .
            docker login -u $DH_USER -p $DH_PASS
            docker push lovohh/lovohhwebsite:$CIRCLE_SHA1


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
